#!/usr/bin/python
##########################################
# native_binner_multiq1.py
#
# 2/13/2015
#
# read in an RT dump file, and generate "binner" plots
#   comparable to the onces generated by hand in excel
#
######################################################

import pandas as pd;
import numpy as np;
import matplotlib as mpl;
## next line must occur before any mpl etc commands or imports
#mpl.use("Qt4Agg")

import matplotlib.pyplot as plt;
import datetime;

print "Start time:", datetime.datetime.today().isoformat()
print "Display mode:", plt.matplotlib.rcParams['backend']

QueueList = ['Feedback', 'HEP', 'HEP_ref_user']

inx = 'c:\\Users\\bhecker\\My Documents\\INSPIRE\\RT metrics\\2014-12-08 analyses\\2014-12-08_RT_dump_results.tsv'

EntireSheet=pd.read_csv(inx, 'RT-2014-12-08_19-59-40_all_manu', delimiter='\t', index_col=None, na_values=['NA'] )

entireSheetQI = EntireSheet.set_index('QueueName')

BIN_START_EPOCH = pd.datetime(2013, 5, 1)  ## modern epoch
#set up weekly range
rng = pd.date_range(start=BIN_START_EPOCH, end=datetime.date.today(), freq='w')


for thisQueueName in QueueList:
    ThisQueueFrame = entireSheetQI.loc[thisQueueName]
    print "Queue length,", thisQueueName,len(ThisQueueFrame)
    ## I didn't see a way to extract the ID column if it was the index
    qFrame = ThisQueueFrame.reset_index()
    idKeys = qFrame['id']
    # set up fresh bin
    tsbin = pd.Series(0, index=rng)
    qFrame = qFrame.set_index('id')

    for k in idKeys:
        c = qFrame.loc[k]['Created']
        y, m, d = c[:10].split('-')
        c = pd.datetime(int(y),int(m),int(d) ) 
        r = qFrame.loc[k]['Resolved'] 
        if r == "Not set": 
            r = pd.datetime(2020, 12, 31)
        else:
            y, m, d = r[:10].split('-')
            r = pd.datetime(int(y), int(m), int(d) )

        for beginBin in tsbin.index:
            ## bin is an entire week -- careful comparison
            ## ticket starts before or equal to "endBin" date, 
            ## and ends on or after the beginBin date. 

            if c <= beginBin+datetime.timedelta(days=6) and r >= beginBin:
                tsbin.loc[beginBin] += 1

    print "====>",thisQueueName,"tsbin tail/head", tsbin.head(), tsbin.tail()

    ## plot ##############

    #get_ipython().magic(u'matplotlib inline')
    #print plt.matplotlib.rcParams['backend']
    plt.figure();

    plt.ylabel("number of tickets"); 
    plt.title(thisQueueName + " Queue Size")
    tsbin.plot(kind='line')
    #next line forces the y axis to originate at zero
    plt.ylim(0,)

    plt.savefig('02'+thisQueueName+'.png', dpi=140, facecolor='w', format='png')

print "End time:", datetime.datetime.today().isoformat()
